### ISSUE TITLE
netbox: API_TOKEN creation fails for dragon user

### ISSUE THREAD

**Issue by grawert** [osism/ansible-collection-services#421]
User creation fails when the API_TOKEN is created. This affects the `dragon` user.

```
netbox_1         | 🧬  loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬  loaded config '/etc/netbox/config/extra.py'
netbox_1         | 🧬  loaded config '/etc/netbox/config/gunicorn_config.py'
netbox_1         | 🧬  loaded config '/etc/netbox/config/logging.py'
netbox_1         | 🧬  loaded config '/etc/netbox/config/plugins.py'
netbox_1         | ▶️  Running the startup script /opt/netbox/startup_scripts/000_users.py
netbox_1         | 👤 Created user dragon
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
netbox_1         |     return self.cursor.execute(sql, params)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django_prometheus/db/common.py", line 71, in execute
netbox_1         |     return super().execute(*args, **kwargs)
netbox_1         | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(40)
netbox_1         |
netbox_1         |
netbox_1         | The above exception was the direct cause of the following exception:
netbox_1         |
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
netbox_1         |     output = self.handle(*args, **options)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 93, in handle
netbox_1         |     exec(sys.stdin.read(), globals())
netbox_1         |   File "<string>", line 1, in <module>
netbox_1         |   File "/usr/lib/python3.9/runpy.py", line 285, in run_path
netbox_1         |     return _run_code(code, mod_globals, init_globals,
netbox_1         |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
netbox_1         |     exec(code, run_globals)
netbox_1         |   File "/opt/netbox/netbox/../startup_scripts/__main__.py", line 27, in <module>
netbox_1         |     runpy.run_path(f.path)
netbox_1         |   File "/usr/lib/python3.9/runpy.py", line 268, in run_path
netbox_1         |     return _run_module_code(code, init_globals, run_name,
netbox_1         |   File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
netbox_1         |     _run_code(code, mod_globals, init_globals,
netbox_1         |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
netbox_1         |     exec(code, run_globals)
netbox_1         |   File "/opt/netbox/startup_scripts/000_users.py", line 21, in <module>
netbox_1         |     Token.objects.create(user=user, key=user_details["api_token"])
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
netbox_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
netbox_1         |     obj.save(force_insert=True, using=self.db)
netbox_1         |   File "/opt/netbox/netbox/users/models.py", line 217, in save
netbox_1         |     return super().save(*args, **kwargs)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
netbox_1         |     self.save_base(using=using, force_insert=force_insert,
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
netbox_1         |     updated = self._save_table(
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
netbox_1         |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
netbox_1         |     return manager._insert(
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
netbox_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
netbox_1         |     return query.get_compiler(using=using).execute_sql(returning_fields)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
netbox_1         |     cursor.execute(sql, params)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
netbox_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
netbox_1         |     return executor(sql, params, many, context)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
netbox_1         |     return self.cursor.execute(sql, params)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
netbox_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
netbox_1         |     return self.cursor.execute(sql, params)
netbox_1         |   File "/opt/netbox/venv/lib/python3.9/site-packages/django_prometheus/db/common.py", line 71, in execute
netbox_1         |     return super().execute(*args, **kwargs)
netbox_1         | django.db.utils.DataError: value too long for type character varying(40)
netbox_1         |
```

**Comment by grawert** [comment]
The bug has been fixed with the latest 1.5.1 release.
